<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_orders = $this->getOrders(); ?>
<div class="page-title">
    <h1><?php echo $this->__('My Invoices') ?></h1>
</div>
<?php echo $this->getChildHtml('info');?>
<?php echo $this->getPagerHtml(); ?>
<?php if($_orders->getSize()): ?>
<table class="data-table orders" id="my-orders-table">
    <col width="1" />
    <col width="1" />
    <col />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <thead>
        <tr>
            <th class="number"><?php echo $this->__('Order #') ?></th>
            <th class="date"><?php echo $this->__('Date') ?></th>
            <th class="ship"><?php echo $this->__('Ship To') ?></th>
            <th class="total"><span class="nobr"><?php echo $this->__('Order Total') ?></span></th>
            <th class="view"><span class="nobr"><?php echo $this->__('Invoice #') ?></span></th>
            <th class="view"><span class="nobr"><?php echo $this->__('Credit Memos #') ?></span></th>
        </tr>
    </thead>
    <tbody>
        <?php $_odd = ''; ?>
        <?php foreach ($_orders as $_order): ?>
        <tr>
            <td class="number"><?php echo $_order->getRealOrderId() ?></td>
            <td class="date"><span class="nobr"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></span></td>
            <td class="ship"><?php echo $_order->getShippingAddress() ? $this->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
            <td class="total"><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
            <td class="view">
                <?php $invoices = $this->getInvoices($_order->getId());?>
                <?php $toalInvoice = $invoices->getSize();?>
                <?php if($toalInvoice >= 1):?>
                    <?php foreach($invoices as $invoice): ?>
                        <span class="nobr"><?php echo $invoice->getIncrementId(); ?> <?php echo $this->__('|') ?> <a href="<?php echo $this->getInvoicePrintUrl($invoice) ?>"><?php echo $this->__('Download') ?></a></span>
                    <?php endforeach;?>
                <?php else:?>
                    <span class="nobr"><?php echo $this->__('-') ?></span>
                <?php endif;?>
            </td>
            <td class="view">
                <?php $creditmemos = $this->getCreditmemos($_order->getId());?>
                <?php $toalCreditmemos = $creditmemos->getSize();?>
                <?php if($toalCreditmemos >= 1):?>
                    <?php foreach($creditmemos as $creditmemo): ?>
                        <span class="nobr"><?php echo $creditmemo->getIncrementId(); ?> <?php echo $this->__('|') ?> <a href="<?php echo $this->getCreditMemoPrintUrl($creditmemo) ?>"><?php echo $this->__('Download') ?></a></span>
                    <?php endforeach;?>
                <?php else:?>
                    <span class="nobr"><?php echo $this->__('-') ?></span>
                <?php endif;?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('my-orders-table');</script>
<?php echo $this->getPagerHtml(); ?>
<?php else: ?>
    <p><?php echo $this->__('You have placed no orders.'); ?></p>
<?php endif ?>
