<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * BSS Commerce does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * BSS Commerce does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   BSS
 * @package    Bss_FastOrder
 * @author     Extension Team
 * @copyright  Copyright (c) 2014-2015 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
$_helper = $this->helper('catalog/output');
$_product = $this->getProduct();
/*$_options = Mage::helper('core')->decorateArray($this->getOptions());*/
?>
<!--<dl>
    <?php /*foreach($_options as $_option): */?>
        <?php /*echo $this->getOptionHtml($_option) */?>
    <?php /*endforeach; */?>
    </dl>-->
<?php if($_product->getTypeId() == "configurable"):
    $conf = Mage::getModel('catalog/product_type_configurable')->setProduct($_product);
    $simple_collection = $conf->getUsedProductCollection()->addAttributeToSelect('*')->addFilterByRequiredOptions();
    foreach($simple_collection as $simple_product){
        echo $simple_product->getSku() . " - " . $simple_product->getName() . " - " . Mage::helper('core')->currency($simple_product->getPrice()) . "<br>";
    }
endif;
die;
$requestUrl=$this->getRequest()->getRequestString();    
?>
<?php if(Mage::helper('fastorder')->checkVersion()) :?>
    <script src="<?php echo $this->getSkinUrl('js/bss/product-fastorder-18.js');?>" type="text/javascript"></script>
<?php else:?>
    <script src="<?php echo $this->getSkinUrl('js/bss/product-fastorder-19.js');?>" type="text/javascript"></script>
<?php endif;?>

<script type="text/javascript">
    optionsPrice2 = optionsPrice;
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<script type="text/javascript">
    var productSelectForm = new VarienForm('product_select_form');
</script>
<?php 
    if(Mage::helper('fastorder')->isEnable()) :
        $no_configurable = false;
        if($_GET['no_configurable'] && $_GET['no_configurable'] == 1) $no_configurable = true;
?>
    <script type="text/javascript">
        var row = "<?php echo Mage::getSingleton('fastorder/session')->getRowFastOrder() ?>";
        if(jQuery('.fastorder-product-view .special-price').length > 0) {
            price_first = jQuery('.fastorder-product-view .special-price .price:first').text();
        }else {
            price_first = jQuery('.fastorder-product-view .price-box .price:first').text();
        }
        var fastorder_currency = priceFormat.pattern.replace('%s', '');
        price_first = price_first.replace(fastorder_currency,"");
        if ($$('div#MB_window input[type="file"]').length==0) {
            var form_select = jQuery("#product_select_form");
            var no_configurable = '<?php echo $no_configurable?>';
            productSelectForm.submit = function(e) {
                if (this.validator.validate()) {
                    if(jQuery('.fastorder-product-view .special-price').length > 0) {
                        price = jQuery('.fastorder-product-view .special-price .price:first').text();
                    }else {
                        price = jQuery('.fastorder-product-view .price-box .price:first').text();
                    }
                    if(jQuery('.fastorder-product-view .tier-prices').length > 0){
                        var priceTier;
                        price_last = price.replace(fastorder_currency,"");
                        price_option = price_last - price_first;
                        jQuery('#fastorder_form #fastorder-'+row+' .price_group .tierprice').each(function() {
                            price_old = jQuery(this).val();
                            price_new = parseFloat(price_old) + parseFloat(price_option);
                            jQuery(this).val(price_new);
                        });
                    }
                    text = '';
                    jQuery('.fastorder-product-view .product-options dt label').each(function() {
                        if(jQuery(this).parent().next().find('select').children('option:selected').text()){
                            textSelected = jQuery(this).text();
                            if(jQuery(this).parent().next().find('select').children('option:selected').text() && jQuery(this).parent().next().find('select').val()){
                                jQuery(this).parent().next().find('select').children('option:selected').each(function () {
                                    text += textSelected + ': ' + jQuery(this).text() + '<br>';
                                })
                            }
                        }
                        if(jQuery(this).parent().next().find("input[type=radio]").length > 0){
                            textRadio = jQuery(this).text();
                            jQuery(this).parent().next().find("input[type=radio]").each(function(){
                                if(jQuery(this).prop('checked')){
                                    text += textRadio + ': ' + jQuery(this).next().text() + '<br>';
                                }
                            });
                        }
                        if(jQuery(this).parent().next().find("textarea").length > 0){
                            textTextarea = jQuery(this).text();
                            if(jQuery(this).parent().next().find("textarea").val()){
                                text += textTextarea + ': ' + jQuery(this).parent().next().find("textarea").val() + '<br>';
                            }
                        }
                        if(jQuery(this).parent().next().find("input[type=text]").length > 0){
                            textInput = jQuery(this).text();
                            if(jQuery(this).parent().next().find("input[type=text]").val()){
                                text += textInput + ': ' + jQuery(this).parent().next().find("input[type=text]").val() + '<br>';
                            }
                        }
                        if(jQuery(this).parent().next().find("input[type=checkbox]").length > 0){
                            textLabel = jQuery(this).text();
                            jQuery(this).parent().next().find("input[type=checkbox]").each(function(){
                                if(jQuery(this).prop('checked')){
                                    text += textLabel + ': ' + jQuery(this).next().text() + '<br>';
                                }
                            });
                        }
                    });
                    text = text.replace(/\*/g,' ');
                    fastorder_options(row,price,text,1);
                    var url = '';
                    if(no_configurable){
                        url = "<?php echo $this->getUrl('fastorder/ajax/customSimpleOption'); ?>";
                    }else{
                        url = "<?php echo $this->getUrl('fastorder/ajax/saveOption'); ?>";
                    } 
                    jQuery.ajax({
                        url: url,
                        data: {items: form_select.serialize(),row: row},
                        success: function () {
                            jQuery.fancybox_fastorder.close();
                        }
                    });
                }
            }.bind(productSelectForm);
        } else {
            $('is_input_file').value = 1;
        }   
        jQuery(document).on('click','.fancybox-close',function(){
            fastorder_reset(row);
        });
    </script>
<?php endif?>

<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="fastorder-product-view">
    <form action="" method="post" id="product_select_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <div class="product-shop">
            <div class="product-img-box">
                <?php
                $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(70).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
                echo $_helper->productAttribute($_product, $_img, 'image');
                ?>
            </div>
            <div class="product-details">
                <div class="product-name">
                    <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                </div>
                <?php echo $this->getChildHtml('product_type_data') ?>
                <?php echo $this->getTierPriceHtml() ?>
                <!-- <?php //echo $this->getPriceHtml($_product); ?> -->
                <?php echo $this->getChildHtml('extrahint') ?>

                <?php if (!$this->hasOptions()):?>
                    <div class="add-to-box">
                        <?php if($_product->isSaleable()): ?>
                            <?php echo $this->getChildHtml('addtocart') ?>
                        <?php endif; ?>
                    </div>
                    <?php echo $this->getChildHtml('extra_buttons') ?>
                <?php else: ?>
                    <?php echo $this->getChildHtml('addto') ?>
                <?php endif; ?>
            </div>
            <div class="clearer"></div>
            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
            <?php endif;?>
        </div>
        <div class="clearer"></div>
        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
            <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
        <?php endif;?>
    </form>
</div>
