<div class="register-page">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <div class="register-title">
        <h4><?php echo $this->__('WHOLESALE REGISTRATION')?></h4>
        <p>Thanks for your interest in our products. Please fill out the form below to register for a wholesale account. Approved account will have access to our online order system. If you are an existing wholesale customer and need to place an order with us, please <a class="b2b-signin-modal" href="<?php echo Mage::helper('customer')->getLoginUrl()?>">login here.</a></p>
    </div>
   <form id="b2b-register-form" method="post" action="<?php echo $this->getPostUrl()?>" enctype="multipart/form-data">
        <?php echo $this->getChildHtml('account.register.storeinfo');?>
        <div class="register-separator"></div>
        <?php echo $this->getChildHtml('account.register.shipping');?>
        <div class="register-separator"></div>
        <?php echo $this->getChildHtml('account.register.billing');?>
        <div class="register-separator"></div>
        <?php echo $this->getChildHtml('account.register.additional');?>
        <div class="register-actions b2b-overflow">
            <p class="left">* Required Fields</p>
            <button class="b2b-button right"><span><span><?php echo $this->__('SUBMIT FOR APPROVAL')?></span></span></button>
        </div>
    </form>
     <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('b2b-register-form', true);
    //]]>
    </script>
</div>