<div class="b2b-overflow">
    <h5><?php echo $this->__('ADDITIONAL CONTACTS')?></h5>
    
    
    
        <div class="b2b-overflow">
            <div class="left left-column">
                <div class="input-box">
                    <label><?php echo $this->__('Owner / Manager First Name')?></label>
                    <div>
                        <input type="text" name="add[owner_firstname]" class=""/>
                    </div>
                </div>
            </div>
            <div class="right right-column">
                <div class="input-box">
                    <label><?php echo $this->__('Owner / Manager Last Name')?></label>
                    <div>
                        <input type="text" name="add[owner_lastname]"  class=""/>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="b2b-overflow">
            <div class="left left-column">
                <div class="combo-box">
                    <div class="input-box left">
                        <label><?php echo $this->__('Phone Number')?></label>
                        <div>
                            <input type="text" name="add[owner_telephone]" class="" />
                        </div>
                    </div>
                    
                    <div class="input-box right">
                        <label><?php echo $this->__('Fax Number')?></label>
                        <div>
                            <input type="text" name="add[owner_fax]" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="right right-column">
                <div class="input-box">
                    <label><?php echo $this->__('Email Address')?></label>
                    <div>
                        <input type="text" name="add[owner_email]" class=" validate-email"/>
                    </div>
                </div>
            </div>
        </div>
        
    <div class="clear"></div>
    <div class="register-separator internal-separator"></div>
    
    
    
        <div class="b2b-overflow">
            <div class="left left-column">
                <div class="input-box">
                <label><?php echo $this->__('Buyer First Name')?></label>
                <div>
                    <input type="text" name="add[buyer_firstname]" class=""/>
                </div>
            </div>
            </div>
            <div class="right right-column">
                <div class="input-box">
                <label><?php echo $this->__('Buyer Last Name')?></label>
                <div>
                    <input type="text" name="add[buyer_lastname]" class=""/>
                </div>
            </div>
            </div>
        </div>
        
        
        <div class="b2b-overflow">
            <div class="left left-column">
                <div class="combo-box">
                <div class="input-box left">
                    <label><?php echo $this->__('Phone Number')?></label>
                    <div>
                        <input type="text" name="add[buyer_telephone]" class=""/>
                    </div>
                </div>
                
                <div class="input-box right">
                    <label><?php echo $this->__('Fax Number')?></label>
                    <div>
                        <input type="text" name="add[buyer_fax]"/>
                    </div>
                </div>
            </div>
            </div>
            <div class="right right-column">
                <div class="input-box">
                <label><?php echo $this->__('Email Address')?></label>
                <div>
                    <input type="text" name="add[buyer_email]" class="validate-email"/>
                </div>
            </div>
            </div>
        </div>
    
    
        
    
    <div class="clear"></div>
    <div class="register-separator internal-separator"></div>
    
    
        <div class="b2b-overflow">
            <div class="left left-column">
                <div class="input-box">
                <label><?php echo $this->__('Assistant Buyer First Name')?></label>
                <div>
                    <input type="text" name="add[assistant_firstname]" class=""/>
                </div>
            </div>
            </div>
            <div class="right right-column">
                <div class="input-box">
                <label><?php echo $this->__('Assistant Buyer Last Name')?></label>
                <div>
                    <input type="text" name="add[assistant_lastname]" class=""/>
                </div>
            </div>
            </div>
        </div>
        <div class="b2b-overflow">
            <div class="left left-column">
                <div class="combo-box">
                <div class="input-box left">
                    <label><?php echo $this->__('Phone Number')?></label>
                    <div>
                        <input type="text" name="add[assistant_telephone]" class=""/>
                    </div>
                </div>
                
                <div class="input-box right">
                    <label><?php echo $this->__('Fax Number')?></label>
                    <div>
                        <input type="text" name="add[assistant_fax]" />
                    </div>
                </div>
            </div>
            </div>
            <div class="right right-column">
                <div class="input-box">
                <label><?php echo $this->__('Email Address')?></label>
                <div>
                    <input type="text" name="add[assistant_email]" class="validate-email"/>
                </div>
            </div>
            </div>
        </div>
        
    
    <div class="clear"></div>
    <div class="register-separator internal-separator"></div>
    
    
    <div class="b2b-overflow">
            <div class="left left-column">
                <div class="input-box">
                <label><?php echo $this->__('Accounts Payable Contact First Name')?></label>
                <div>
                    <input type="text" name="add[accounts_firstname]" class=""/>
                </div>
            </div>
            </div>
            <div class="right right-column">
                <div class="input-box">
                <label><?php echo $this->__('Accounts Payable Contact Last Name')?></label>
                <div>
                    <input type="text" name="add[accounts_lastname]" class=""/>
                </div>
            </div>
            </div>
        </div>
        
        
        <div class="b2b-overflow">
            <div class="left left-column">
                <div class="combo-box">
                <div class="input-box left">
                    <label><?php echo $this->__('Phone Number')?></label>
                    <div>
                        <input type="text" name="add[accounts_telephone]" class=""/>
                    </div>
                </div>
                
                <div class="input-box right">
                    <label><?php echo $this->__('Fax Number')?></label>
                    <div>
                        <input type="text" name="add[accounts_fax]"/>
                    </div>
                </div>
            </div>
            </div>
            <div class="right right-column">
                <div class="input-box">
                <label><?php echo $this->__('Email Address')?></label>
                <div>
                    <input type="text"  name="add[accounts_email]" class="validate-email"/>
                </div>
            </div>
            </div>
        </div>
        
   
       <div class="clear"></div>
    <div class="register-separator internal-separator"></div>
</div>