<?php 
    $_collectionList = $this->getItems();
    $_helper = $this->helper('catalog/output');
    $_helperb2b = $this->helper('b2b');
$i=0;
?>
<div class="table-body" id="b2b-all-product">
            
                <?php foreach ($_collectionList as $_product):?>
                    <?php
                    //$modelProduct = Mage::getModel('catalog/product')->load($_product->getId());
                    //$_product = $modelProduct;?>
                    <?php $info = $this->getQtyInCart($_product->getId());?>
                    <?php $type=$_product->getTypeId();?>
                    <div class="table-row b2b-<?php echo $type?>_product">                
                        <div class="left download-icon">
                          <?php if ($_helperb2b->isDownload($_product->getId())):?><a href="" data-id="<?php echo $_product->getId()?>" class="download-icon-link"></a><?php endif;?>
                        </div>
                        
                        
                        <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                        <div class="left name-product">
                            <h3 data-id="<?php echo $_product->getId()?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></h3>
                        </div>
                        
                        <?php $sku =  $_product->getSku()?>                       
                        <div class="left product-sku"  <?php if (strlen($sku)>12):?>data-toggle="tooltip" data-placement="auto" title="<?php echo $sku?>"<?php endif?> data-id="<?php echo $_product->getId()?>"><?php echo $sku = $_product->getSku()?></div>
                        
                       <div class="left product-available">
                             <?php $_productUpdate = $_product;?>
                             <?php if($_product->isSaleable()): ?>
                                <?php if (in_array($type, array('bundle','configurable','grouped'))):?>
                                    <?php echo $this->__('In Stock')?>
                                <?php else:?>
                                    <?php if (Mage::helper('b2b')->isBackOrder($_productUpdate)):?>
                                        <?php echo $this->__('Backorder')?>
                                    <?php else:?>
                                        <?php
                                         $stock = Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product);
                                         echo $qty =  (int)$stock->getQty(); ?>
                                    <?php endif;?>
                                <?php endif;?>
                             <?php else:?>
                                 <?php echo $this->__('Out of Stock')?>
                             <?php endif;?>
                        </div>
                        <?php $_product->setData('price_view', 1);
//                        $modelProduct = Mage::getModel('catalog/product')->load($_product->getId());?>
                        <div class="left product-price">
                            <strong><?php echo $this->getPriceHtml($_product, true) ?></strong>
                            <?php $tierPrice =  $this->getTierPriceHtml($_product);$tierPrice = trim($tierPrice); ?>
                            <?php if (!empty($tierPrice)):?>
                                <i>*<?php echo $tierPrice?></i>                               
                            <?php endif;?>
                        </div>
                        
                        <div class="left product-qty">
                        <?php if($_product->isSaleable()): ?>
                        <?php if (in_array($type, array('simple','virtual')) && !$this->hasOptions($_product)):?>
                             <input type="text" value="<?php echo $info['qty']?>" data-quote-id="<?php echo $info['id']?>" data-action="<?php if ($info['id']==0):?>add<?php else:?>update<?php endif;?>" data-id="<?php echo $_product->getId()?>" class="b2b-quick-qty" />
                        <?php else:?>
                            <a href="" class="add-icon b2b-load-product" data-id="<?php echo $_product->getId();?>"></a>
                        <?php endif;?>
                        <?php endif;?>
                        </div>   
                        
                        <div class="clear"></div>
                         
                        <?php echo $this->getSubItemsHtml($_product);?>
                        
                        <?php if (Mage::helper('b2b')->isBackOrder($_productUpdate) || !$_productUpdate->isSaleable()):?>
                        <?php $messageAttribute = Mage::getStoreConfig('b2b/product/message');?>
                        <?php if (!empty($messageAttribute)):?>
                            <?php $message =  $_product->getData($messageAttribute) ?>
                            <?php if (!empty($message)):?>
                                <div class="sub-row sub-row-comment b2b-overflow">
                                    <div class="comment">
                                    <em>*</em><p><?php echo $message?></p>
                                    </div>                                                
                                    <div class="clear"></div>
                                </div>     
                            <?php endif?>
                        <?php endif?>
                    <?php endif?>
                        
                        
                                              
                    </div>
                    
                    
                <?php $i++; endforeach;?>
                <script>
                IWD.List.nextPage = <?php echo $this->_nextPage;?>;
                IWD.List.stopLoad = <?php echo $this->_stopLoad;?>;
                IWD.Decorator.tierPrice();
                </script>
            
                    
            </div>