<div class="account-forgotpassword">

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
    <div class="fieldset">
       
        <p><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
        <ul class="form-list">
            <li>
                <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                <div class="input-box">
                    <input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
                </div>
            </li>
        </ul>
    </div>
   <div class="signin-actions">
        <!-- p class="back-link"><a href="<?php echo $this->helper('customer')->getLoginUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back to Login') ?></a></p>
        <button type="submit" title="<?php echo $this->__('Submit') ?>" class="signin-btn-small btn-right"><?php echo $this->__('Submit') ?></button -->
        
        <button type="submit"  class="button btn-submit" title="<?php echo $this->__('SUBMIT') ?>"><?php echo $this->__('SUBMIT') ?></button>
		<a  class="button btn-back-login" title="<?php echo $this->__('BACK TO LOGIN') ?>" id="back-to-login"><?php echo $this->__('BACK TO LOGIN') ?></a>
		
        
        
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
</div>