<?php $_helper = Mage::helper('signin');?>
<div class="login-form">

	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	<form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
		<div class="row">
			<div class="login-input">
				<label for="email" class="required"><?php echo $this->__('Email Address') ?><em>*</em></label>
				<input type="text" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
			</div>
			
		    <div class="login-input">
				<label for="pass" class="required"><?php echo $this->__('Password') ?><em>*</em></label>
				<input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
			</div>
		</div>	
		<div class="clear"></div>
		<div class="f-p"><a href="<?php echo $this->getForgotPasswordUrl() ?>" id="forgot-password" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a></div>
		<div class="clear"></div>
		<?php echo $this->getChildHtml('persistent.remember.me'); ?>
		<div class="clear"></div>
		<div class="signin-actions">
			 <a  class="button btn-login" title="<?php echo $this->__('Login') ?>" id="signin-login"><?php echo $this->__('Login') ?></a>
			 <a  class="button" title="<?php echo $this->__('Create an Account') ?>" id="create-account-singup"><?php echo $this->__('Create an Account') ?></a>
		</div>		
          <button type="submit" class="hidden"></button>
    </form>
    
   <?php echo $this->getChildHtml('signin.socials')?>
	
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
    //]]>
    </script>
</div>
