<?php 
    $_collectionList = $this->getItems();
    $_size= $this->getFullSize();
    $_helper = $this->helper('catalog/output');
    $_helperb2b = $this->helper('b2b');
?>
<div class="table-body">
            <?php if ($_collectionList!=false && $_collectionList->Count() > 0):?>
                <?php foreach ($_collectionList as $_product):?>                 
                    <?php $_product = Mage::getModel('catalog/product')->load($_product->getId());?>
                    <?php $info = $this->getQtyInCart($_product->getId());?>
                    <?php $type=$_product->getTypeId();?>
                    <div class="table-row b2b-<?php echo $type?>_product">                
                        <div class="left download-icon">
                        <?php if ($_helperb2b->isDownload($_product->getId())):?><a href="" data-id="<?php echo $_product->getId()?>" class="download-icon-link"></a><?php endif;?>
                        </div>
                        
                        
                        <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                        <div class="left name-product">
                            <h3 data-id="<?php echo $_product->getId()?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></h3>
                        </div>
                        
                       
                        
                        <?php $sku =  $_product->getSku()?>                       
                        <div class="left product-sku"  <?php if (strlen($sku)>=12):?>data-toggle="tooltip" data-placement="auto" title="<?php echo $sku?>"<?php endif?> data-id="<?php echo $_product->getId()?>"><?php echo $sku = $_product->getSku()?></div>
                        
                        <div class="left product-available">
                             <?php $_productUpdate = Mage::getModel('catalog/product')->load($_product->getId());?>
                             <?php if($_product->isSaleable()): ?>
                                <?php if (in_array($type, array('bundle','configurable','grouped'))):?>
                                    <?php echo $this->__('In Stock')?>
                                <?php else: ?>
                                    <?php if (Mage::helper('b2b')->isBackOrder($_productUpdate)): ?>
                                        <?php echo $this->__('Backorder')?>
                                    <?php else:?>
                                        <?php $qty =  $_productUpdate->getStockItem()->getQty(); $qty = round($qty, 2);echo $qty = str_replace('.', ',', $qty)?>
                                    <?php endif;?>
                                <?php endif;?>
                             <?php else:?>
                                 <?php echo $this->__('Out of Stock')?>
                             <?php endif;?>                             
                        </div>
                        <?php $_product->setData('price_view', 1)?>
                        <div class="left product-price">
                            <strong><?php echo $this->getPriceHtml($_product, true) ?></strong>
                            <?php $tierPrice =  $this->getTierPriceHtml($_product);$tierPrice = trim($tierPrice); ?>
                            <?php if (!empty($tierPrice)):?>
                                <i>*<?php echo $tierPrice?></i>                               
                            <?php endif;?>
                        </div>
                        
                        <div class="left product-qty">
                        <?php if($_product->isSaleable() || Mage::helper('b2b')->isBackOrder($_product)): ?>
                        <?php if (in_array($type, array('simple','virtual')) && !$this->hasOptions($_product)):?>
                             <input type="text" value="<?php echo $info['qty']?>" data-quote-id="<?php echo $info['id']?>" data-action="<?php if ($info['id']==0):?>add<?php else:?>update<?php endif;?>" data-id="<?php echo $_product->getId()?>" class="b2b-quick-qty" />
                        <?php else:?>
                            <a href="" class="add-icon b2b-load-product" data-id="<?php echo $_product->getId();?>"></a>
                        <?php endif;?>
                        <?php endif;?>
                        </div>
                        
                        <div class="clear"></div>
                        
                        <?php echo $this->getSubItemsHtml($_product);?> 
                        
                        
                        
                    <?php if (Mage::helper('b2b')->isBackOrder($_productUpdate  ) || !$_product->isSaleable()):?>
                        <?php $messageAttribute = Mage::getStoreConfig('b2b/product/message');?>
                        <?php if (!empty($messageAttribute)):?>
                            <?php $message =  $_product->getData($messageAttribute) ?>
                            <?php if (!empty($message)):?>
                                <div class="sub-row sub-row-comment b2b-overflow">
                                    <div class="comment">
                                    <em>*</em><p><?php echo $message?></p>
                                    </div>                                                
                                    <div class="clear"></div>
                                </div>     
                            <?php endif?>
                        <?php endif?>
                    <?php endif?>
                                             
                    </div>
                    
                    
                <?php endforeach;?>
                <script>
                IWD.Decorator.tierPrice();
                </script>            
                <?php endif;?>  
            </div>