<?php
	$_rootCatId = Mage::app()->getStore()->getRootCategoryId();
	$_rootCategory  = Mage::getModel('catalog/category')->load($_rootCatId);
	$collection = $_rootCategory->getChildrenCategories();
?>
<?php if(count($collection)):?>
	<ul class="clearer">
		<?php foreach($collection as $cat):?>
			<li><a href="<?php echo $cat->getUrl()?>"><?php echo $cat->getName();?></a></li>
		<?php endforeach;?>
		<li class="level0"><a class="level0" href="<?php echo $this->getUrl('static') ?>"><?php echo $this->__('About') ?></a></li>
	</ul>
<?php endif;?>