<div class="footer-facebook-widget">
	<div id="fb-root"></div>
	<script>
	document.observe("dom:loaded", function(){
		(function(d, s, id) {
		  var js, fjs = d.getElementsByTagName(s)[0];
		  if (d.getElementById(id)) return;
		  js = d.createElement(s); js.id = id;
		  js.src = "//connect.facebook.net/us_US/sdk.js#xfbml=1&appId=601520193257290&version=v2.0";
		  fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));
	});</script>
	<div class="fb-like" data-href="https://www.facebook.com/iwdagency" data-layout="standard" data-width="240px" data-action="like" data-show-faces="false" data-share="true"></div>
	</div>