<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'Rumbleship\\Test\\' => array($vendorDir . '/rumbleship/php-gateway-client/tests'),
    'Rumbleship\\' => array($vendorDir . '/rumbleship/php-gateway-client/src'),
);
