<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit00c14df3e341cf82db0afb327b9674f6
{
    public static $prefixLengthsPsr4 = array (
        'R' => 
        array (
            'Rumbleship\\Test\\' => 16,
            'Rumbleship\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Rumbleship\\Test\\' => 
        array (
            0 => __DIR__ . '/..' . '/rumbleship/php-gateway-client/tests',
        ),
        'Rumbleship\\' => 
        array (
            0 => __DIR__ . '/..' . '/rumbleship/php-gateway-client/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'R' => 
        array (
            'Requests' => 
            array (
                0 => __DIR__ . '/..' . '/rmccue/requests/library',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit00c14df3e341cf82db0afb327b9674f6::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit00c14df3e341cf82db0afb327b9674f6::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit00c14df3e341cf82db0afb327b9674f6::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
