<?php $_helper = Mage::helper('signin');?>
<?php if ($_helper->isFacebookLoginEnable() || $_helper->isGoogleLoginEnable() || $_helper->isTwitterLoginEnable() || $_helper->isYahooLoginEnable() || $_helper->isPaypalLoginEnable()):?>
<div class="socials-login">
	<h4><?php echo $this->__('Or login with...')?></h4>
    		
	<?php if ($_helper->isFacebookLoginEnable()):?>
		<a class="btn-facebook-login" onclick="IWD.Signin.loginWithFacebook();return false;"><?php echo $this->__('Facebook')?></a>
	<?php endif;?>
        	
	<?php if ($_helper->isGoogleLoginEnable()):?>
		<a class="btn-google-login" id="signinButton" href="<?php echo Mage::getModel('signin/google')->getAuthUrl();?>"><?php echo $this->__('Google+')?></a>
	<?php endif;?>
        
	<?php if ($_helper->isTwitterLoginEnable()):?>
		<a class="btn-twitter-login"><?php echo $this->__('Twitter')?></a>
	<?php endif;?>
        	
	<?php if ($_helper->isYahooLoginEnable()):?>
		<a class="btn-yahoo-login"><?php echo $this->__('yahoo')?></a>
	<?php endif;?>
        	
	<?php if ($_helper->isPaypalLoginEnable()):?>
		<a class="btn-paypal-login" href="<?php echo Mage::helper('signin/paypal')->getPopUpLoginUrl()?>"><?php echo $this->__('PayPal')?></a>
	<?php endif?>
        
</div>
	
<?php endif;?>