<div class="b2b-overflow">
    <h5><?php echo $this->__('Shipping address')?></h5>
    
        <div class="b2b-overflow">
            <div class="left left-column">
                <div class="input-box">
                    <label><?php echo $this->__('Address 1')?><em>*</em></label>
                    <div>
                        <input type="text" name="shipping[street][]" class="required-entry" />
                    </div>
                </div>
            </div>
            <div class="right right-column">
                <div class="input-box">
                    <label><?php echo $this->__('Address 2')?></label>
                    <div>
                        <input type="text" name="shipping[street][]"/>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="b2b-overflow">
            <div class="left left-column">
                <div class="input-box">
                    <label><?php echo $this->__('City')?><em>*</em></label>
                    <div>
                        <input type="text" name="shipping[city]" class="required-entry"/>
                    </div>
                </div>
            </div>
            <div class="right right-column">
                <div class="combo-box">
                    <div class="input-box left">
                        <label><?php echo $this->__('State')?><em>*</em></label>
                        <div>
                             <select id="region_id" name="shipping[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                                    <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                </select>
                                <script type="text/javascript">
                                //<![CDATA[
                                    $('region_id').setAttribute('defaultValue', "null");
                                //]]>
                                </script>
                                <input type="text" id="region" name="shipping[region]" value="<?php echo $this->escapeHtml($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                        </div>
                    </div>
                    
                    <div class="input-box right">
                        <label><?php echo $this->__('Zipcode')?><em>*</em></label>
                        <div>
                            <input type="text" name="shipping[postcode]" class="required-entry"/>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        
        <div class="b2b-overflow">
            <div class="left left-column">
                <div class="input-box">
                    <label><?php echo $this->__('Country')?><em>*</em></label>
                    <div>
                        <?php echo $this->getCountryHtmlSelect($defValue=null, $name='shipping[country_id]', $id='country', $title='Country') ?>
                    </div>
                </div>
            </div>
            <div class="right right-column">
                <div class="input-box">
                    <label><?php echo $this->__('Number of Locations')?></label>
                    <div>
                        <input type="text" name="add[number_location]" />
                    </div>
                </div>
            </div>
        </div>
        
        
        <!--<div class="b2b-overflow">
            <div class="left left-column">
                <div class="input-box">
                    <label><?php /*echo $this->__('FedEx Account Number')*/?></label>
                    <div>
                        <input type="text" name="add[fedex]"/>
                    </div>
                </div>
            </div>
            <div class="right right-column">
                <div class="input-box">
                    <label><?php /*echo $this->__('UPS Account Number')*/?></label>
                    <div>
                        <input type="text" name="add[ups]"/>
                    </div>
                </div>
            </div>
        </div>-->
        
         
    

</div>

<script type="text/javascript">
    //<![CDATA[
        var shiping = new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
    //]]>
</script>