<div class="b2b-overflow">
        <h5><?php echo $this->__('Store INFO')?></h5>
        <div class="clear"></div>
        
        <div class="b2b-overflow">
            <div class="left left-column">
                <div class="input-box">
                    <label><?php echo $this->__('Store Name')?><em>*</em></label>
                    <div>
                        <input type="text" name="info[store_name]" id="store_name" class="required-entry" />
                    </div>
                </div>
            </div>
            <div class="right right-column">
                <div class="input-box input-box-770-2">
                    <label><?php echo $this->__('Type of Business')?> <small><?php echo $this->__('(check all that apply)')?></small></label>
                    <div class="checkbox-box">
                        <label><input type="checkbox" name="info[type_business][]" value="<?php echo $this->__('E-commerce')?>" /><?php echo $this->__('E-commerce')?></label>
                        <label><input type="checkbox" name="info[type_business][]" value="<?php echo $this->__('Brick & Mortar')?>"  /><?php echo $this->__('Brick & Mortar')?></label>
                        <label class="label-770"><input type="checkbox" name="info[type_business][]" value="<?php echo $this->__("Men's")?>"  /><?php echo $this->__("Bicycle Shop")?></label>
                        <label><input type="checkbox" name="info[type_business][]" value="<?php echo $this->__("Women's")?>"  /><?php echo $this->__("Other")?></label>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="b2b-overflow">
            <div class="left left-column">
                <div class="input-box input-box-770">
                    <label><?php echo $this->__('Primary Contact First Name')?><em>*</em></label>
                    <div>
                        <input type="text" name="account[firstname]" class="required-entry" />
                    </div>
                </div>
            </div>
            <div class="right right-column">
                <div class="input-box">
                    <label><?php echo $this->__('Primary Contact Last Name')?><em>*</em></label>
                    <div>
                        <input type="text" name="account[lastname]" class="required-entry" />
                    </div>
                </div>
            </div>
        </div>
        
        
        <div class="b2b-overflow">
            <div class="left left-column">
                <div class="combo-box">
                    <div class="input-box left">
                        <label><?php echo $this->__('Phone Number')?><em>*</em></label>
                        <div>
                            <input type="text" name="address[telephone]" class="required-entry" />
                        </div>
                    </div>
                    
                    <div class="input-box right">
                        <label><?php echo $this->__('Fax Number')?></label>
                        <div>
                            <input type="text"  name="address[fax]"/>
                        </div>
                    </div>
                </div>
            </div>
            <div class="right right-column">
                <div class="input-box">
                    <label><?php echo $this->__('Email Address')?><em>*</em></label>
                    <div>
                        <input type="text" name="account[email]" class="required-entry validate-email" />
                    </div>
                </div>
            </div>
        </div>
        
        
        
        <div class="b2b-overflow">
            <div class="left left-column">
                 <div class="input-box">
                    <label><?php echo $this->__('Password')?><em>*</em></label>
                    <div>
                        <input type="password" id="password" name="account[password]" class="required-entry validate-password" />
                    </div>
                </div>
            </div>
            <div class="right right-column">
                <div class="input-box">
                    <label><?php echo $this->__('Confirm Password')?><em>*</em></label>
                    <div>
                        <input type="password" name="account[confirmation]" class="required-entry validate-cpassword" />
                    </div>
                </div>
            </div>
        </div>
        
        
        
        <div class="b2b-overflow">
            <div class="left left-column">
                <div class="input-box">
                    <label><?php echo $this->__('Tax ID Number / SSN / F-EIN')?><em>*</em></label>
                    <div>
                        <input type="text" name="info[ssn]" class="required-entry" />
                    </div>
                </div>
            </div>
            <div class="right right-column">
                <div class="input-box">
                    <label><?php echo $this->__('Wholesale / Resale Certificate')?><em>*</em></label>
                    <div>
                        <input type="file" name="certificate" id="certificate" class="required-entry" />
                    </div>
                </div>
            </div>
        </div>
        
        
        <div class="input-box">
                <label class="class_line"><?php echo $this->__('Primary Classification')?> <small><?php echo $this->__('(check all that apply)')?></small></label>

                <div class="checkbox-box checkbox-long">
                    <label><input type="checkbox" name="info[classification][]" value="<?php echo $this->__('Independent shops')?>" /><?php echo $this->__('Independent shops')?></label>
                    <label><input type="checkbox" name="info[classification][]" value="<?php echo $this->__('Chain outlets')?>" /><?php echo $this->__('Chain outlets')?></label>
                    <label class="label-980"><input type="checkbox" name="info[classification][]" value="<?php echo $this->__('Boutique / Lifestyle')?>" /><?php echo $this->__('Boutique / Lifestyle')?></label>
                    <label class="label-all"><input type="checkbox" name="info[classification][]" value="<?php echo $this->__('Specialty: MTB, Road, Triathlon, etc.')?>" /><?php echo $this->__('Specialty: MTB, Road, Triathlon, etc.')?></label>
                    <label class="label-980"><input type="checkbox" name="info[classification][]" value="<?php echo $this->__('Outdoor or general sporting stuff')?>" /><?php echo $this->__('Outdoor or general sporting stuff')?></label>
                    <label class="label-all"><input type="checkbox" name="info[classification][]" value="<?php echo $this->__("We're in the city")?>" /><?php echo $this->__("We're in the city")?></label>
                    <label class="label-980"><input type="checkbox" name="info[classification][]" value="<?php echo $this->__("We're in the 'burbs")?>" /><?php echo $this->__("We're in the 'burbs")?></label>
                    <label><input type="checkbox" name="info[classification][]" value="<?php echo $this->__("We're in the sticks")?>" /><?php echo $this->__("We're in the sticks")?></label>
                    <div class="limit-to-column">
                        <label class="last"><input type="checkbox"  name="info[classification][]" value="<?php echo $this->__('Other')?>" /><?php echo $this->__('Your best description:')?></label>
                        <input type="text" name="info[classification][other]" />
                    </div>
                </div>
            </div>        
    </div>