<?php $_helperText = Mage::helper('b2b/text');?>
<div class="b2b-modal fade signin" id="b2b-signin-modal" tabindex="-1" role="dialog"  aria-hidden="true">
  <div class="b2b-modal-dialog">
    <div class="b2b-modal-content">
      <div class="b2b-modal-body">        
        <a class="close" data-dismiss="modal"><i class="fa fa-times-circle"></i></a>
		
		
		<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()):?>
    
		<div class="b2b-dialog-title">
		  <h5><?php echo $_helperText->getText('login_form/text1');?></h5>
		</div>
		<div id="b2b-login-form" class="b2b-login-form">
		  <form id="login-form" method="post" enctype="application/x-www-form-urlencoded">
			 <div class="box-input">
			     <label><?php echo $this->__('Email Address')?><em>*</em></label>
			     <div class="">
			         <input type="text" name="login[username]" value="" id="email" class="required-entry validate-email"/>
			     </div>
			 </div>
			 
			 <div class="box-input">
			     <label><?php echo $this->__('Password')?><em>*</em></label>
			     <div class="">
			         <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass"/>
			     </div>
			 </div>
			 <div class="b2b-overflow b2b-dialog-note">
			     <a href="" class="left" id="b2b-forgot-password"><?php echo $this->__('Forgot password?')?></a>
			     
			     <p class="right"><?php echo $this->__('* Required Fields')?></p>
			 </div>
			 
			 <div class="b2b-overflow b2b-dialog-action">
			     <p class="left"><?php echo $_helperText->getText('login_form/text2');?></p>
			     
			     <button type="submit" class="hidden"></button>
			     <a class="right btn-login" id="signin-login"><?php echo $this->__('Login')?></a>
			 </div>
			 
			 <div class="register">
			     <h6><?php echo $_helperText->getText('login_form/text3');?></h6>
			     <a href="<?php echo $this->getRegisterUrl();?>"><?php echo $_helperText->getText('login_form/text4');?></a>
			 </div>
		  </form>
		  </div>
		  

            <div id="b2b-forgot-form" class="b2b-forgot-form hidden">
                <form method="post" id="form-validate-forgot" autocomplete="off">
                    <div>
                        <h2><?php echo $this->__('Forgot your password?') ?></h2>
                        <p><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
                        <ul class="form-list">
                            <li>
                                <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                                <div class="input-box">
                                    <input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
                                </div>
                            </li>
                            <?php echo $this->getChildHtml('form.additional.info'); ?>
                        </ul>
                    </div>
                    <div class="buttons-set">
                        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                        <p class="back-link" id="back-link-login"><a><?php echo $this->__('Back to Login') ?></a></p>
                        <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
                    </div>
                </form>
            </div>
            
            <?php else:?>
               <div class="b2b-logout-form">
                <h4><?php echo $this->__('Are you sure you want to log out?')?></h4>
                <div class="b2b-logout-actions">
                    <a class="back-close" data-dismiss="modal"><?php echo $this->__('Back')?></a>
                    <a class="logout-close" href="<?php echo $this->getUrl('customer/account/logout')?>"><?php echo $this->__('Logout')?></a>
                </div>
               </div> 
            <?php endif?>
		
		
		
      </div>
      
    </div>
  </div>
</div>

<script type="text/javascript">
    //<![CDATA[
        var loginForm = new VarienForm('login-form', true);
    //]]>
</script>

<div class="b2b-ajax-loader"></div>