<div class="b2b-selected-items">
    <div class="b2b-table-scroll">
    <div class="div-table">
        <?php echo $this->getHeadHtml();?>
        <?php echo $this->getBodyHtml();?>
        <div class="table-footer">
            <a class="right" href="" id="b2b-back-queue"><?php echo $this->__('Back to top')?></a>
        </div>              
    </div>
    </div>
</div>
<script>
pageType = 'prev';
IWD.Decorator.tierPrice();
</script>