<?php 
/**
 * Magedelight
 * Copyright (C) 2014  Magedelight <info@magedelight.com>
 *
 * NOTICE OF LICENSE
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see http://opensource.org/licenses/gpl-3.0.html.
 *
 * @category   Ktpl
 * @package    Ktpl_Catalogprint
 * @copyright  Copyright (c) 2014 Mage Delight (http://www.magedelight.com/)
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU General Public License, version 3 (GPL-3.0)
 * @author     Magedelight <info@magedelight.com>
 */
?>
<?php if(Mage::getStoreConfig('catalogprint/general/enable_backend') == '1'): ?>
<?php $storeId = $this->getRequest()->getParam('store',null) ?>
<?php $isStoreCodeAppended = (boolean)Mage::getStoreConfig('web/url/use_store') ?>

<?php if(!$storeId): ?>
<?php
foreach(Mage::app()->getWebsites(false) as $_website):
if($_website->getIsDefault()){
$storeId = $_website->getDefaultStore()->getId();
break;
}
endforeach;
 ?>
<?php endif; ?>
<?php $isFrontendSecure = (boolean)Mage::getStoreConfig('web/secure/use_in_frontend',$storeId) ?>
<?php $storeUrl = (!$isFrontendSecure) ? Mage::getStoreConfig('web/unsecure/base_url',$storeId): Mage::getStoreConfig('web/secure/base_url',$storeId) ?>
<?php if($isStoreCodeAppended): ?>
<?php $storeUrl .= Mage::app()->getStore($storeId)->getCode().'/' ?>
<?php endif; ?>
<script type="text/javascript">
function sendPrintRequest(categoryId){
    var valueObj = {};
    $('printoptions-container').select('input[type="checkbox"], select').each(function(el){
        
        var elementId = el.id;
        var elementName = elementId.replace(/cp_/,'');
        if(el.nodeName == 'SELECT'){
            //alert(el.value);
            if(el.value != ''){
                valueObj[elementName] = el.value;
            }
        }else{
            if(el.checked){
                valueObj[elementName] = el.value;
            }
        }
    });
    valueObj['store'] = <?php echo $storeId ?>;
    if($('store_switcher') != undefined){
        valueObj['store'] = ($('store_switcher').getValue() == '') ? <?php echo $storeId ?>: $('store_switcher').getValue();
    }
    var queryString = $H(valueObj).toQueryString();
    var urlSlash = queryString.replace(/&/g,'/').replace(/=/g,'/');
    var url = '<?php echo $storeUrl.'catalog-print/index/index/' ?>'+urlSlash+'/category/'+categoryId;
    window.open(url,'_blank');
}
</script>
<?php endif; ?>
