<div class="b2b-modal fade download-dialog" id="b2b-download-modal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="b2b-modal-dialog">
		<div class="b2b-modal-content">
			<div class="b2b-modal-body">
				<a class="close" data-dismiss="modal"><i class="fa fa-times-circle"></i></a>
				<div id="b2b-dialog-download"></div>
				<div class="b2b-modal-footer">
				    <div class="left">
					   <a href="" class="btn-small" data-dismiss="modal"><?php echo $this->__('Cancel')?></a>
					</div>
					<div class="right">
					   <div class="selected-item">ITEMS SELECTED   <strong>0</strong></div>
					   <a href="" class="btn-download"><span></span><?php echo $this->__('Download')?></a>
					</div>
					<div class="clear"></div>
				</div>
			</div>

		</div>
	</div>
</div>