<?php
	$product = $this->getData('product');
	$update = $this->getData('updateProduct');
	if (!$update){
		$message = Mage::helper('checkout')->__('%s was added to your shopping cart.', Mage::helper('core')->htmlEscape($product->getName()));
	}else{
		$message = Mage::helper('checkout')->__('Item was updated in your shopping cart.');
	}
?>
<div class="aac-messages" style="display:block">
	<p class="aac-message-success"><?php echo $message?></p>
</div>

<div class="es-action">
	<a class="aac-button es-btn-checkout" href="<?php echo Mage::helper('checkout/url')->getCheckoutUrl()?>"><?php echo $this->__('Checkout')?></a>
	<a class="aac-button right close-ajax-dialog"><?php echo $this->__('Continue Shopping')?></a>
</div>