<?php 
$params = Mage::getModel('customer/session')->getReorderParams();
$filter = new Varien_Object();
$sort = 'asc';
if ($params!=null){
    $filter->addData($params);
}

if ($params['sort']=='asc'){
    $sort = 'desc';
}
?>
<div class="table-header ">
                <div class="fixed-wrapper">
                    <form id="b2b-filter-reorder">
                        <div class="left th-reorder-product">
                            <a href="" data-attribute="name" <?php if ($params['attribute']=='name'):?>data-sort="<?php echo $sort?>"<?php else:?>data-sort="asc"<?php endif;?>>
                            <?php echo $this->__('Product')?><?php if ($params['attribute']=='name'):?><i class="fa <?php if($params['sort'] == 'asc') echo 'fa-arrow-down '; else echo 'fa-arrow-up '; echo $params['sort']; ?>"></i><?php endif;?>
                            </a>
                            <div ><input type="text" name="name" value="<?php echo $filter->getName()?>"/></div>
                        </div>
                        <div class="left th-reorder-sku">
                            <a href="" data-attribute="sku" <?php if ($params['attribute']=='sku'):?>data-sort="<?php echo $sort?>"<?php else:?>data-sort="asc"<?php endif;?>>
                            <?php echo $this->__('Sku')?><?php if ($params['attribute']=='sku'):?><i class="fa <?php if($params['sort'] == 'asc') echo 'fa-arrow-down '; else echo 'fa-arrow-up '; echo $params['sort']; ?>"></i><?php endif;?>
                            </a>
                            <div ><input type="text" name="sku" value="<?php echo $filter->getSku()?>"/></div>
                        </div>
                        
                        <div class="left th-reorder-previous">
                            <a data-sort="no-sortable"  class="no-sortable" data-attribute="qty" <?php if ($params['attribute']=='qty'):?>data-sort="<?php echo $sort?>"<?php else:?>data-sort="asc"<?php endif;?>>
                            <?php echo $this->__('PREVIOUS QTY')?><?php if ($params['attribute']=='qty'):?><i class="fa <?php if($params['sort'] == 'asc') echo 'fa-arrow-down '; else echo 'fa-arrow-up '; echo $params['sort']; ?>"></i><?php endif;?>
                            </a>
                            <div ><input type="text" name="qty[from]" value="<?php echo $filter->getQty(0)?>"/> <span class="left">-</span> <input type="text" name="qty[to]" value="<?php echo $filter->getQty(1)?>"/></div>
                        </div>
                        
                        <div class="left th-reorder-available">
                            <a data-sort="no-sortable" class="no-sortable">
                            <?php echo $this->__('Available')?>
                            </a>
                            <div ><input type="text" name="" value=""/></div>
                        </div>
                        
                        <div class="left th-reorder-price">
                            <a href="" data-attribute="price" <?php if ($params['attribute']=='price'):?>data-sort="<?php echo $sort?>"<?php else:?>data-sort="asc"<?php endif;?>>
                            <?php echo $this->__('Price')?><?php if ($params['attribute']=='price'):?><i class="fa <?php if($params['sort'] == 'asc') echo 'fa-arrow-down '; else echo 'fa-arrow-downup '; echo $params['sort']; ?>"></i><?php endif;?>
                            </a>
                            <div><input type="text" name="price[from]"  value="<?php echo $filter->getPrice('from')?>"/></div><span>-</span>
                            <div><input type="text" name="price[to]"  value="<?php echo $filter->getPrice('to')?>"/></div>
                        </div>
                        
                        <div class="left th-reorder-qty">
                            <a data-sort="no-sortable"  class="no-sortable"><?php echo $this->__('Qty')?></a>
                            <div ><input type="text"/></div><span>-</span><div ><input type="text" /></div>
                        </div>
                    </form>
                    <div class="clear"></div>
                </div>
                <div class="b2b-header-shadow"></div>
</div>
<div class="botex"></div> 