<?php 
    $_collectionList = $this->getItems();
    $_helper = $this->helper('catalog/output');
    $_helperb2b = $this->helper('b2b');
    $quoteId = $this->_getCart()->getQuote()->getId();
    $qty = Mage::app()->getRequest()->getParam('qty', array());
    $from = false;
    $to = false;

    if (is_array($qty)){
       
      $from = isset($qty['from'])?$qty['from']:false;
      $to = isset($qty['to'])?$qty['to']:false;
    }
?>
<?php if (count($_collectionList)>0 ):?>
    <div class="table-body" id="b2b-reorder-table">
        <?php foreach ($_collectionList as $item):?>
          
            <?php $_product = Mage::getModel('catalog/product')->load($item['product_id']);?>
            
            <?php $type=$_product->getTypeId();?>
            
            <?php $_data = $this->getSubItems($item);?>
            
            <?php 
                if ($from!=false){
                    if ($from<$_data['qty']){
                        continue;
                    }
                }
            ?>
            
             <?php 
                if ($to!=false){
                    if ($to>$_data['qty']){
                        continue;
                    }
                }
            ?>
            
            
            <div class="table-row b2b-<?php echo $type?>_product">                
                        <div class="left download-icon">
                        <?php if ($_helperb2b->isDownload($_product->getId())):?><a href="" data-id="<?php echo $_product->getId()?>" class="download-icon-link"></a><?php endif;?>
                        </div>
                        
                        
                        <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                        <div class="left reorder-product">
                            <h3 data-id="<?php echo $_product->getId()?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></h3>                            
                        </div>
                         
                        <?php $sku =  $_product->getSku()?>                       
                        <div class="left reorder-sku"  <?php if (strlen($sku)>=12):?>data-toggle="tooltip" data-placement="auto" title="<?php echo $sku?>"<?php endif?> data-id="<?php echo $_product->getId()?>"><?php echo $sku = $_product->getSku()?></div>
                        
                        <div class="left reorder-previous"><?php echo (int)$_data['qty']?></div>
                        
                        <div class="left product-available">
                             <?php $_productUpdate = Mage::getModel('catalog/product')->load($_product->getId())?>                             
                             <?php if($_product->isSaleable()): ?>
                                <?php if (in_array($type, array('bundle','configurable','grouped'))):?>
                                    <?php echo $this->__('In Stock')?>
                                <?php else:?>
                                    <?php if (Mage::helper('b2b')->isBackOrder($_productUpdate)):?>
                                        <?php echo $this->__('Backorder')?>
                                    <?php else:?>
                                        <?php echo $qty =  (int)$_productUpdate->getStockItem()->getQty(); ?>
                                    <?php endif;?>
                                <?php endif;?>                                
                             <?php endif;?>                             
                        </div>
                        
                        <?php $_product->setData('price_view', 1)?>
                        <div class="left reorder-price">
                            <strong><?php echo $this->getPriceHtml($_product, true) ?></strong>
                            <?php $tierPrice =  $this->getTierPriceHtml($_product);$tierPrice = trim($tierPrice); ?>
                            <?php if (!empty($tierPrice)):?>
                                <i>*<?php echo $tierPrice?></i>
                               
                            <?php endif;?>
                        </div>
                        
                        <div class="left reorder-qty">
                        <?php if($_product->isSaleable() || Mage::helper('b2b')->isBackOrder()): ?>
                        <?php if (in_array($type, array('simple','virtual')) && !$this->hasOptions($_product)):?>
                             <?php $quoteData = $this->getDataCurrentQuote($item)?>  
                             <?php if ($quoteId==$item['quote_id']):?>
                                <input type="text" value="<?php echo $item['qty']?>" data-quote-id="<?php echo $item['quote_id']?>" data-action="update" data-id="<?php echo $_product->getId()?>" class="b2b-quick-qty" />
                             <?php else:?>                 
                                <?php $requestedItem = $this->checkProductInCurrentQuote($_product)?>
                                <?php if ($requestedItem==false):?>                                                  
                                    <input type="text" value="0" data-status="1" data-item="<?php echo $item['item_id']?>" data-quote-id="<?php echo $item['quote_id']?>" data-action="add" data-id="<?php echo $item['product_id']?>" class="b2b-quick-qty" />
                                <?php else:?>
                                    <input type="text" value="<?php echo $requestedItem->getQty()?>"  data-quote-id="<?php echo  $requestedItem->getId()?>" data-action="update" data-id="<?php echo $requestedItem->getProductId()?>" class="b2b-quick-qty" />
                                <?php endif?>
                             <?php endif;?>
                        <?php else:?>
                            <a href="" class="add-icon b2b-load-product" data-id="<?php echo $_product->getId();?>"></a>
                        <?php endif;?>
                        <?php endif;?>
                        </div>
                        <div class="clear"></div>
                        
                        <?php echo $this->getSubItemsHtml($_data['collection'], $_product);?>
                        
                        <?php if (Mage::helper('b2b')->isBackOrder($_product) || !$_product->isSaleable()):?>
                        <?php $messageAttribute = Mage::getStoreConfig('b2b/product/message');?>
                        <?php if (!empty($messageAttribute)):?>
                            <?php $message =  $_product->getData($messageAttribute) ?>
                            <?php if (!empty($message)):?>
                                <div class="sub-row sub-row-comment b2b-overflow">
                                    <div class="comment">
                                    <em>*</em><p><?php echo $message?></p>
                                    </div>                                                
                                    <div class="clear"></div>
                                </div>     
                            <?php endif?>
                        <?php endif?>
                    <?php endif?>
            </div>
        <?php endforeach;?>
    </div>
<?php else:?>
    <div class="table-row"> 
        <p class="empty-result"><?php echo $this->__('No product matches with this query.')?></p>
    </div>
<?php endif;?>
