<?php echo $this->getChildHtml('b2b.subheader');?>
    <?php $paramsFilter = Mage::getModel('customer/session')->getPrevParams();?>
    <div class="b2b-quick-order">
        <div class="b2b-overflow">
            <h3 class="left"><?php echo $this->__('Previously Ordered Items');?></h3>
            <div class="input-daterange input-group right" id="datepicker">
                <input type="text" class="input-sm form-control" id="b2b-from" name="start" value="<?php echo $paramsFilter['from']?>" />
                <span class="input-group-addon">to</span>
                <input type="text" class="input-sm form-control" id="b2b-to" name="end"  value="<?php echo $paramsFilter['to']?>" />
            </div>
        </div>
    <div id="quick-list-products">
        <?php echo $this->getLayout()->createBlock('b2b/order_list_reorder')->toHtml();?>
    </div>
</div>
