<?php
	$product = $this->getData('product');
	$message = Mage::helper('checkout')->__('%s was added to your wishlist.', Mage::helper('core')->htmlEscape($product->getName()));
?>
<div class="aac-messages" style="display:block">
	<p class="aac-message-success"><?php echo $message?></p>
</div>

<div class="es-action">
	<a class="aac-button es-btn-checkout"><?php echo $this->__('Checkout')?></a>
	<a class="aac-button right close-ajax-dialog"><?php echo $this->__('Continue Shopping')?></a>
</div>