<?php 
/**
 * Magedelight
 * Copyright (C) 2014  Magedelight <info@magedelight.com>
 *
 * NOTICE OF LICENSE
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see http://opensource.org/licenses/gpl-3.0.html.
 *
 * @category   Ktpl
 * @package    Ktpl_Catalogprint
 * @copyright  Copyright (c) 2014 Mage Delight (http://www.magedelight.com/)
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU General Public License, version 3 (GPL-3.0)
 * @author     Magedelight <info@magedelight.com>
 */
?>
<?php $helper = Mage::helper('catalogprint'); ?>
<?php $storeId = $this->getRequest()->getParam('store',null) ?>
<?php $isStoreCodeAppended = (boolean)Mage::getStoreConfig('web/url/use_store') ?>
<?php $groups = Mage::getModel('customer/group')->getCollection()->toOptionHash() ?>
<?php if(!$storeId): ?>
<?php
foreach(Mage::app()->getWebsites(false) as $_website):
if($_website->getIsDefault()){
$storeId = $_website->getDefaultStore()->getId();
break;
}
endforeach;
 ?>
<?php endif; ?>
<?php $isFrontendSecure = (boolean)Mage::getStoreConfig('web/secure/use_in_frontend',$storeId) ?>
<?php $storeUrl = (!$isFrontendSecure) ? Mage::getStoreConfig('web/unsecure/base_url',$storeId): Mage::getStoreConfig('web/secure/base_url',$storeId) ?>
<?php if($isStoreCodeAppended): ?>
<?php $storeUrl .= Mage::app()->getStore($storeId)->getCode().'/' ?>
<?php endif; ?>
<div id="catalogprint-options">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4><?php echo $this->__('Print Options Selections') ?></h4>
        </div>
        <div class="fieldset">
            <div class="hor-scroll">
                <table class="form-list">
                <tbody>
                    <tr>
                        <td class="label"><?php echo $helper->__('Print PDF Catalog Layout View') ?></td>
                        <td class="value">
                            <select id="cp_layout" name="catalogprint[layout]" class="select">
                                <option value="grid"><?php echo $helper->__('Grid Layout') ?></option>
                                <option value="list"><?php echo $helper->__('List Layout') ?></option>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td class="label"><?php echo $helper->__('Select Customer Groups') ?></td>
                        <td class="value">
                            
                            <select id="cp_customer_group_id" name="catalogprint[customer_group_id]" class="select">
                                <option value=""><?php echo $helper->__('-----Select Group-----') ?></option>
                                <?php foreach($groups as $value=>$label): ?>
                                    <option value="<?php echo $value ?>"><?php echo $label ?></option>
                                <?php endforeach; ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2" align="left">
                            <strong><?php echo $helper->__('Print PDF Catalog Options'); ?></strong>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2"><input checked="checked" type="checkbox" name="catalogprint[heading]" id="cp_heading" value="1" />
                        <?php echo $helper->__('Product Categories/Sub Categories Headings') ?></td>
                    </tr>
                    
                    <tr>
                        <td colspan="2"><input checked="checked" type="checkbox" name="catalogprint[cover]" id="cp_cover" value="1" />
                        <?php echo $helper->__('Title/cover page') ?></td>
                    </tr>
                    
                    <tr>
                        <td colspan="2"><input checked="checked" type="checkbox" name="catalogprint[contents]" id="cp_contents" value="1" />
                        <?php echo $helper->__('Table of Contents with page numbers ') ?></td>
                    </tr>
                    
                    <tr>
                        <td colspan="2"><input checked="checked" type="checkbox" name="catalogprint[mfg_asc]" id="cp_mfg_asc" value="1" />
                        <?php echo $helper->__('Document index by Product SKU in ascending order.') ?></td>
                    </tr>
                    
                    <tr>
                        <td colspan="2"><input checked="checked" type="checkbox" name="catalogprint[part_asc]" id="cp_part_asc" value="1" />
                        <?php echo $helper->__('Document index by Product Name in alphabetical sorted ascending order.') ?></td>
                    </tr>
                    
                </tbody>
            </table>
            </div>
        </div>
    </div>
    <script type="text/javascript">
function sendPrintRequest(categoryId){
    var valueObj = {};
    if($('product_categories').getValue() != ''){
        $('catalogprint-options').select('input[type="checkbox"], select').each(function(el){

            var elementId = el.id;
            var elementName = elementId.replace(/cp_/,'');
            if(el.nodeName == 'SELECT'){
                //alert(el.value);
                if(el.value != ''){
                    valueObj[elementName] = el.value;
                }
            }else{
                if(el.checked){
                    valueObj[elementName] = el.value;
                }
            }
        });
        valueObj['store'] = <?php echo $storeId ?>;
        if($('store_switcher') != undefined){
            valueObj['store'] = ($('store_switcher').getValue() == '') ? <?php echo $storeId ?>: $('store_switcher').getValue();
        }
        var queryString = $H(valueObj).toQueryString();
        var urlSlash = queryString.replace(/&/g,'/').replace(/=/g,'/');
        var url = '<?php echo $storeUrl.'catalog-print/index/index/' ?>'+urlSlash+'/category/'+$('product_categories').getValue();
        window.open(url,'_blank');
    }else{
        alert("Please Select Categories for print.");
        return false;
    }
}
</script>
</div>
